version: '3.8'
services:
  zydhan-web-api:
    container_name: zydhan-web-api
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./src:/var/www/html
    env_file: .env
    dns:
      - 1.1.1.1
      - 1.0.0.1
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    networks:
      - nginx-proxy-network
      - mysql-network

networks:
  nginx-proxy-network:
    external: true
  mysql-network:
    external: true
