FROM zydhanlinnar11/laravel-docker-image:latest

RUN docker-php-ext-install pdo pdo_mysql

# Install Xdebug
RUN apk add --no-cache $PHPIZE_DEPS \
    && pecl install xdebug-3.1.5 \
    && docker-php-ext-enable xdebug \
    && touch /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini && printf "zend_extension=xdebug\n\n[xdebug]\nxdebug.mode=develop,debug\nxdebug.client_host=host.docker.internal\nxdebug.start_with_request=yes\n" > /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini \
    && touch /usr/local/etc/php/conf.d/error_reporting.ini && echo "error_reporting=E_ALL" > /usr/local/etc/php/conf.d/error_reporting.ini
    